source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'Jokes' do
  pod 'AFNetworking’
  pod ’SDWebImage’
  pod 'MJRefresh'
  pod ‘Masonry’
  pod ‘JSONModel’
  pod ‘ProgressHUD’
end
